"""Migración inicial.

Revision ID: 154960e14763
Revises: 
Create Date: 2023-08-26 11:22:31.053200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154960e14763'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist')
    # ### end Alembic commands ###
